[tool.black]
line-length = 120

[tool.bandit]
exclude_dirs = ["tests"]

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "envoy_schema"
version = "0.0.1"
dependencies = [
    "pydantic_xml[lxml]",
]

[project.optional-dependencies]
dev = [
    "bandit",
    "flake8",
    "mypy",
    "types-python-dateutil",
    "types-tzlocal",
]

[tool.setuptools.package-data]
"envoy_schema" = ["py.typed"]